--------------------------------------------------------
--  已建立檔案 - 星期一-三月-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENU_MAIN
--------------------------------------------------------

  CREATE TABLE "KB"."MENU_MAIN" 
   (	"MENU_INDEX" NUMBER(20,0), 
	"MENU_NAME" VARCHAR2(20 BYTE), 
	"MENU_ORDER" NUMBER(2,0), 
	"MENU_WAITING_PAGE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KB.MENU_MAIN
SET DEFINE OFF;
Insert into KB.MENU_MAIN (MENU_INDEX,MENU_NAME,MENU_ORDER,MENU_WAITING_PAGE) values (1,'HOME PAGE',1,'waitingPage/homePageW');
Insert into KB.MENU_MAIN (MENU_INDEX,MENU_NAME,MENU_ORDER,MENU_WAITING_PAGE) values (2,'PRACTICE',2,'waitingPage/springPracticeW');
Insert into KB.MENU_MAIN (MENU_INDEX,MENU_NAME,MENU_ORDER,MENU_WAITING_PAGE) values (3,'OTHERS',3,'waitingPage/othersW');
Insert into KB.MENU_MAIN (MENU_INDEX,MENU_NAME,MENU_ORDER,MENU_WAITING_PAGE) values (4,'ABOUT ME',4,'waitingPage/aboutMeW');
--------------------------------------------------------
--  DDL for Index SYS_C007586
--------------------------------------------------------

  CREATE UNIQUE INDEX "KB"."SYS_C007586" ON "KB"."MENU_MAIN" ("MENU_INDEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MENU_MAIN
--------------------------------------------------------

  ALTER TABLE "KB"."MENU_MAIN" ADD PRIMARY KEY ("MENU_INDEX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KB"."MENU_MAIN" MODIFY ("MENU_INDEX" NOT NULL ENABLE);
