--------------------------------------------------------
--  已建立檔案 - 星期一-三月-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENU_DETAIL
--------------------------------------------------------

  CREATE TABLE "KB"."MENU_DETAIL" 
   (	"MENU_DETAIL_INDEX" NUMBER(20,0), 
	"MENU_INDEX" NUMBER(20,0), 
	"MENU_DETAIL_NAME" VARCHAR2(20 BYTE), 
	"MENU_DETAIL_ORDER" NUMBER(2,0), 
	"MENU_DETAIL_DESC" VARCHAR2(200 BYTE), 
	"MENU_FUNCTIONG_PAGE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KB.MENU_DETAIL
SET DEFINE OFF;
Insert into KB.MENU_DETAIL (MENU_DETAIL_INDEX,MENU_INDEX,MENU_DETAIL_NAME,MENU_DETAIL_ORDER,MENU_DETAIL_DESC,MENU_FUNCTIONG_PAGE,CREATE_DATE) values (21,2,'jQuery',3,'jQuery load function','testPage/Test3',to_date('03-2月 -16','DD-MON-RR'));
Insert into KB.MENU_DETAIL (MENU_DETAIL_INDEX,MENU_INDEX,MENU_DETAIL_NAME,MENU_DETAIL_ORDER,MENU_DETAIL_DESC,MENU_FUNCTIONG_PAGE,CREATE_DATE) values (2,2,'vs',2,'is not working with','testPage/Test2',to_date('02-2月 -16','DD-MON-RR'));
Insert into KB.MENU_DETAIL (MENU_DETAIL_INDEX,MENU_INDEX,MENU_DETAIL_NAME,MENU_DETAIL_ORDER,MENU_DETAIL_DESC,MENU_FUNCTIONG_PAGE,CREATE_DATE) values (1,2,'Angularjs',1,'Angularjs','testPage/Test1',to_date('01-2月 -16','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C007606
--------------------------------------------------------

  CREATE UNIQUE INDEX "KB"."SYS_C007606" ON "KB"."MENU_DETAIL" ("MENU_DETAIL_INDEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MENU_DETAIL
--------------------------------------------------------

  ALTER TABLE "KB"."MENU_DETAIL" ADD PRIMARY KEY ("MENU_DETAIL_INDEX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KB"."MENU_DETAIL" MODIFY ("MENU_INDEX" NOT NULL ENABLE);
  ALTER TABLE "KB"."MENU_DETAIL" MODIFY ("MENU_DETAIL_INDEX" NOT NULL ENABLE);
